version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:13.15
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - docker.env

volumes:
  postgres-data: